### ISSUE TITLE
"where clause"

### ISSUE THREAD

**Issue by rotten** [komamitsu/td-fdw#6]
I have observed that the "where" clause is almost never sent through the td-fdw to treasure data.  I have yet to actually see one go through.  Regardless of my query, td-fdw pulls back the entire treasure data table, and then applies the where clause after it has retrieved the whole thing.

This seems really inefficient (even though we generally query materialized views of the TD tables).  Pulling back the entire table to build even a small materialized view of a subset of the data requires lots of processing time at Treasure Data, lots of bandwidth, and lots of disk, and lots of CPU in our database to do the filtering out of a temp table after the fact.

It doesn't work like that with the two FDW's I wrote (the [rethinkdb one](https://github.com/rotten/rethinkdb-multicorn-postgresql-fdw), and the [philips hue one](https://github.com/rotten/hue-multicorn-postgresql-fdw)).  It doesn't happen that way with the [MongoDB YAM FDW](https://github.com/rotten/yam_fdw) either (which I had to fork and fix to get working with our Mongo database).  I'm not sure what is different about the td-fdw code that is waiting to apply filters until after the whole table is retrieved.  I haven't had time to dive into it yet.  Meanwhile, I figured I'd open an issue.

**Comment by komamitsu** [comment]
Can you tell me what kind of query didn't send `where` clause through td-fdw?

The following query sends `where` clause expectedly.
- td-fdw

```
testdb=> SELECT code, count(1)
testdb-> FROM sample_datasets
testdb-> WHERE time BETWEEN 1412121600 AND 1414800000    -- For time index pushdown in Treasure Data
datatank-> GROUP BY code;
 code | count 
------+-------
  404 |    17
  200 |  4981
  500 |     2
(3 rows)
```
- Query in Treasure Data

```
SELECT time,user,host,path,referer,code,agent,size,method FROM www_access WHERE (time >= 1412121600) AND (time <= 1414800000)
```

**Comment by rotten** [comment]
Very similar to your query, however without the count and group by:

select
  col1,
 col2,
 col3
from
  mytable
where
  time > 1414800000
;

When I do this and look at the running job in the TD console, I do not get a where clause.

**Comment by rotten** [comment]
Ok, I did a a few more experiments:

This works (passes the where clause through):

```
select 
  *
from
  my_foreign_table
where
  time > 1477958400
limit 100
```

(Although it doesn't pass the limit through, but I can live with that.)

This does not:

```
select
  *
from
  my_foreign_table
where
  time > extract(epoch from (date_trunc('month', current_timestamp at time zone 'utc')))
limit 100
```

Nor this:

```
select
  *
from
  my_foreign_table
where
  time > (select extract(epoch from (date_trunc('month', current_timestamp at time zone 'utc'))))
limit 100
```

I'm not sure yet if this is a PostgreSQL internal, a Multicorn thing, or something specific to this FDW.  If you have any suggestions for a way to trick this,  please let me know.   It really cripples the queries as well as putting significant extra load on our Treasure Data infrastructure and PostgreSQL database, to have to pull the entire table back every time before the filter is applied.

**Comment by komamitsu** [comment]
Thanks for the testing. In those cases, I saw this FDW didn't receive any conditions from Multicorn. So It seems PostgreSQL or/and Multicorn doesn't pass any condition when users use PostgreSQL functions...

**Comment by rotten** [comment]
Thanks, I'll post this over in the Multicorn issues and see if anyone has suggestions.

**Comment by rotten** [comment]
@komamitsu I had an interesting reply when I posted this issue to the Multicorn folks yesterday.  I'll do some experiments later today to see if that does the trick.

**Comment by rotten** [comment]
Their suggestion worked:

```
select
  *
from
  my_foreign_table
where
  time > extract(epoch from (date_trunc('month', current_timestamp at time zone 'utc')))::int
limit 100
```

Thanks for looking into this with me!

**Comment by komamitsu** [comment]
@rotten Great to hear that! Thanks
